GET http://localhost:3000/api/persons

###
GET http://localhost:3000/api/persons/652ba0b4efe095c8b9bc5c3b

###
DELETE http://localhost:3000/api/persons/1

###
POST http://localhost:3000/api/persons
content-type: application/json

{
  "name": "jacek4",
  "number": "444555666"
}